# Generated by Django 5.2.1 on 2026-01-31 21:54

import apps.core.utils
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Kenyan phone number for login and notifications",
                        max_length=15,
                        unique=True,
                        validators=[apps.core.utils.validate_kenyan_phone],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=True)),
                (
                    "premium_expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When premium access ends (6 hours after payment)",
                        null=True,
                    ),
                ),
                (
                    "account_expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When full account + subjects are deleted (24 hours after payment)",
                        null=True,
                    ),
                ),
                ("is_premium", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                (
                    "cluster_points",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        default=0.0,
                        help_text="User's KCSE cluster points (editable)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "auth_user",
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("USER_REGISTERED", "User Registered"),
                            ("USER_LOGIN", "User Login"),
                            ("USER_LOGOUT", "User Logout"),
                            ("PASSWORD_CHANGED", "Password Changed"),
                            ("PASSWORD_RESET_REQUESTED", "Password Reset Requested"),
                            ("PASSWORD_RESET_COMPLETED", "Password Reset Completed"),
                            ("PROFILE_UPDATED", "Profile Updated"),
                            ("PHONE_VERIFIED", "Phone Verified"),
                            ("PAYMENT_INITIATED", "Payment Initiated"),
                            ("PAYMENT_COMPLETED", "Payment Completed"),
                            ("PAYMENT_FAILED", "Payment Failed"),
                            ("SUBSCRIPTION_CREATED", "Subscription Created"),
                            ("SUBSCRIPTION_CANCELLED", "Subscription Cancelled"),
                            ("REFUND_REQUESTED", "Refund Requested"),
                            ("REFUND_PROCESSED", "Refund Processed"),
                            ("COURSE_VIEWED", "Course Viewed"),
                            ("COURSE_SELECTED", "Course Selected"),
                            ("COURSE_DESELECTED", "Course Deselected"),
                            ("APPLICATION_SUBMITTED", "Application Submitted"),
                            ("APPLICATION_UPDATED", "Application Updated"),
                            ("SUSPICIOUS_ACTIVITY", "Suspicious Activity"),
                            ("ACCOUNT_LOCKED", "Account Locked"),
                            ("ACCOUNT_UNLOCKED", "Account Unlocked"),
                            ("SESSION_REVOKED", "Session Revoked"),
                            ("SECURITY_ALERT", "Security Alert"),
                        ],
                        db_index=True,
                        help_text="Type of action performed",
                        max_length=50,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the action occurred",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(help_text="User's IP address"),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional details about the action",
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=True, help_text="Whether the action was successful"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if action failed"
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        blank=True,
                        default=uuid.uuid4,
                        help_text="Request ID for tracking",
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Activity",
                "verbose_name_plural": "User Activities",
                "db_table": "user_activity",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_ip",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "db_table": "user_profile",
            },
        ),
        migrations.CreateModel(
            name="UserSelectedCourse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_id", models.UUIDField()),
                ("course_name", models.CharField(max_length=300)),
                ("institution", models.CharField(max_length=100)),
                ("is_applied", models.BooleanField(default=False)),
                ("application_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected_courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        db_index=True,
                        help_text="Session or JWT token identifier",
                        max_length=255,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(help_text="User's IP address"),
                ),
                ("user_agent", models.TextField(help_text="User's browser user agent")),
                (
                    "device_type",
                    models.CharField(
                        blank=True,
                        help_text="Device type (mobile, tablet, desktop)",
                        max_length=20,
                    ),
                ),
                (
                    "browser",
                    models.CharField(
                        blank=True, help_text="Browser name", max_length=50
                    ),
                ),
                (
                    "os",
                    models.CharField(
                        blank=True, help_text="Operating system", max_length=50
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, help_text="Country based on IP", max_length=50
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, help_text="City based on IP", max_length=100
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the session is currently active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Session creation time"
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        auto_now=True, help_text="Last activity timestamp"
                    ),
                ),
                (
                    "logout_time",
                    models.DateTimeField(
                        blank=True, help_text="Session logout time", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Session",
                "verbose_name_plural": "User Sessions",
                "db_table": "user_session",
            },
        ),
        migrations.CreateModel(
            name="UserSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B", "B"),
                            ("B-", "B-"),
                            ("C+", "C+"),
                            ("C", "C"),
                            ("C-", "C-"),
                            ("D+", "D+"),
                            ("D", "D"),
                            ("D-", "D-"),
                            ("E", "E"),
                        ],
                        help_text="Grade achieved in the subject",
                        max_length=2,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="Reference to the subject",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.subject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Subject",
                "verbose_name_plural": "User Subjects",
                "db_table": "user_subject",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["phone_number"], name="auth_user_phone_n_baf3e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active", "is_verified"], name="auth_user_is_acti_29b1d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["date_joined"], name="auth_user_date_jo_f1a394_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["user", "action"], name="user_activi_user_id_e71375_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["timestamp"], name="user_activi_timesta_85b358_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["ip_address"], name="user_activi_ip_addr_df0e04_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["success"], name="user_activi_success_ca8f9e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userselectedcourse",
            index=models.Index(
                fields=["user", "content_type", "object_id"],
                name="authenticat_user_id_e91662_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userselectedcourse",
            unique_together={("user", "content_type", "object_id")},
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["user", "is_active"], name="user_sessio_user_id_4f7411_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["session_key"], name="user_sessio_session_ab559f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["ip_address"], name="user_sessio_ip_addr_b87514_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["created_at"], name="user_sessio_created_4bbdd5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersubject",
            index=models.Index(fields=["user"], name="user_subjec_user_id_a17fdd_idx"),
        ),
        migrations.AddIndex(
            model_name="usersubject",
            index=models.Index(
                fields=["subject"], name="user_subjec_subject_89940d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersubject",
            index=models.Index(fields=["grade"], name="user_subjec_grade_337940_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="usersubject",
            unique_together={("user", "subject")},
        ),
    ]
