# Generated by Django 5.2.1 on 2025-06-06 07:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="User's email address (used for login)",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(help_text="User's first name", max_length=30),
                ),
                (
                    "last_name",
                    models.CharField(help_text="User's last name", max_length=30),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Kenyan phone number for M-Pesa and notifications",
                        max_length=15,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be in format: '+254712345678'",
                                regex="^\\+254[17]\\d{8}$",
                            )
                        ],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into admin site",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user has verified their email",
                    ),
                ),
                (
                    "is_premium",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user has premium subscription",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date when the user joined the platform",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, help_text="Last login timestamp", null=True
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "auth_user",
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("USER_REGISTERED", "User Registered"),
                            ("USER_LOGIN", "User Login"),
                            ("USER_LOGOUT", "User Logout"),
                            ("PASSWORD_CHANGED", "Password Changed"),
                            ("PASSWORD_RESET_REQUESTED", "Password Reset Requested"),
                            ("PASSWORD_RESET_COMPLETED", "Password Reset Completed"),
                            ("EMAIL_VERIFIED", "Email Verified"),
                            ("PROFILE_UPDATED", "Profile Updated"),
                            ("PHONE_VERIFIED", "Phone Verified"),
                            ("PAYMENT_INITIATED", "Payment Initiated"),
                            ("PAYMENT_COMPLETED", "Payment Completed"),
                            ("PAYMENT_FAILED", "Payment Failed"),
                            ("SUBSCRIPTION_CREATED", "Subscription Created"),
                            ("SUBSCRIPTION_CANCELLED", "Subscription Cancelled"),
                            ("REFUND_REQUESTED", "Refund Requested"),
                            ("REFUND_PROCESSED", "Refund Processed"),
                            ("COURSE_VIEWED", "Course Viewed"),
                            ("COURSE_SELECTED", "Course Selected"),
                            ("COURSE_DESELECTED", "Course Deselected"),
                            ("APPLICATION_SUBMITTED", "Application Submitted"),
                            ("APPLICATION_UPDATED", "Application Updated"),
                            ("SUSPICIOUS_ACTIVITY", "Suspicious Activity"),
                            ("ACCOUNT_LOCKED", "Account Locked"),
                            ("ACCOUNT_UNLOCKED", "Account Unlocked"),
                            ("SESSION_REVOKED", "Session Revoked"),
                            ("SECURITY_ALERT", "Security Alert"),
                        ],
                        db_index=True,
                        help_text="Type of action performed",
                        max_length=50,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the action occurred",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(help_text="User's IP address"),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional details about the action",
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=True, help_text="Whether the action was successful"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if action failed"
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        blank=True, help_text="Request ID for tracking", max_length=100
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Activity",
                "verbose_name_plural": "User Activities",
                "db_table": "user_activity",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, help_text="User's date of birth", null=True
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("O", "Other"),
                            ("", "Prefer not to say"),
                        ],
                        help_text="User's gender",
                        max_length=1,
                    ),
                ),
                (
                    "county",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("nairobi", "Nairobi"),
                            ("mombasa", "Mombasa"),
                            ("kisumu", "Kisumu"),
                            ("nakuru", "Nakuru"),
                            ("eldoret", "Eldoret"),
                            ("thika", "Thika"),
                            ("malindi", "Malindi"),
                            ("kitale", "Kitale"),
                            ("garissa", "Garissa"),
                            ("kakamega", "Kakamega"),
                            ("other", "Other"),
                        ],
                        help_text="User's county of residence",
                        max_length=20,
                    ),
                ),
                (
                    "preferred_study_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("online", "Online"),
                            ("hybrid", "Hybrid"),
                        ],
                        help_text="Preferred mode of study",
                        max_length=20,
                    ),
                ),
                (
                    "preferred_location",
                    models.CharField(
                        blank=True, help_text="Preferred study location", max_length=100
                    ),
                ),
                (
                    "career_interests",
                    models.TextField(
                        blank=True, help_text="User's career interests and goals"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="User's profile picture",
                        null=True,
                        upload_to="avatars/",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="User's biography", max_length=500
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, help_text="Receive email notifications"
                    ),
                ),
                (
                    "sms_notifications",
                    models.BooleanField(
                        default=False, help_text="Receive SMS notifications"
                    ),
                ),
                (
                    "marketing_emails",
                    models.BooleanField(
                        default=False, help_text="Receive marketing emails"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "db_table": "user_profile",
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        db_index=True,
                        help_text="Session or JWT token identifier",
                        max_length=255,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(help_text="User's IP address"),
                ),
                ("user_agent", models.TextField(help_text="User's browser user agent")),
                (
                    "device_type",
                    models.CharField(
                        blank=True,
                        help_text="Device type (mobile, tablet, desktop)",
                        max_length=20,
                    ),
                ),
                (
                    "browser",
                    models.CharField(
                        blank=True, help_text="Browser name", max_length=50
                    ),
                ),
                (
                    "os",
                    models.CharField(
                        blank=True, help_text="Operating system", max_length=50
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, help_text="Country based on IP", max_length=50
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, help_text="City based on IP", max_length=100
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the session is currently active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Session creation time"
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        auto_now=True, help_text="Last activity timestamp"
                    ),
                ),
                (
                    "logout_time",
                    models.DateTimeField(
                        blank=True, help_text="Session logout time", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Session",
                "verbose_name_plural": "User Sessions",
                "db_table": "user_session",
            },
        ),
        migrations.CreateModel(
            name="UserSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject_name",
                    models.CharField(help_text="Name of the subject", max_length=100),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B", "B"),
                            ("B-", "B-"),
                            ("C+", "C+"),
                            ("C", "C"),
                            ("C-", "C-"),
                            ("D+", "D+"),
                            ("D", "D"),
                            ("D-", "D-"),
                            ("E", "E"),
                        ],
                        help_text="Grade achieved in the subject",
                        max_length=2,
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(help_text="Year the exam was taken"),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("kcse", "KCSE"),
                            ("igcse", "IGCSE"),
                            ("ib", "International Baccalaureate"),
                            ("sat", "SAT"),
                            ("other", "Other"),
                        ],
                        default="kcse",
                        help_text="Type of examination",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Subject",
                "verbose_name_plural": "User Subjects",
                "db_table": "user_subject",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="auth_user_email_ece7f7_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active", "is_verified"], name="auth_user_is_acti_29b1d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["date_joined"], name="auth_user_date_jo_f1a394_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["user", "action"], name="user_activi_user_id_e71375_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["timestamp"], name="user_activi_timesta_85b358_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["ip_address"], name="user_activi_ip_addr_df0e04_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["success"], name="user_activi_success_ca8f9e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["user", "is_active"], name="user_sessio_user_id_4f7411_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["session_key"], name="user_sessio_session_ab559f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["ip_address"], name="user_sessio_ip_addr_b87514_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["created_at"], name="user_sessio_created_4bbdd5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersubject",
            index=models.Index(
                fields=["user", "year"], name="user_subjec_user_id_ce062c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersubject",
            index=models.Index(
                fields=["subject_name"], name="user_subjec_subject_302917_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersubject",
            index=models.Index(fields=["grade"], name="user_subjec_grade_337940_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="usersubject",
            unique_together={("user", "subject_name", "year", "exam_type")},
        ),
    ]
