# Generated by Django 5.2.1 on 2025-07-21 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userselectedcourse",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.course"
            ),
        ),
        migrations.AddField(
            model_name="userselectedcourse",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="selected_courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usersession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usersubject",
            name="subject",
            field=models.ForeignKey(
                help_text="Reference to the subject",
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.subject",
            ),
        ),
        migrations.AddField(
            model_name="usersubject",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["phone_number"], name="auth_user_phone_n_baf3e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active", "is_verified"], name="auth_user_is_acti_29b1d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["date_joined"], name="auth_user_date_jo_f1a394_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["user", "action"], name="user_activi_user_id_e71375_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["timestamp"], name="user_activi_timesta_85b358_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["ip_address"], name="user_activi_ip_addr_df0e04_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["success"], name="user_activi_success_ca8f9e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userselectedcourse",
            unique_together={("user", "course")},
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["user", "is_active"], name="user_sessio_user_id_4f7411_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["session_key"], name="user_sessio_session_ab559f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["ip_address"], name="user_sessio_ip_addr_b87514_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["created_at"], name="user_sessio_created_4bbdd5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersubject",
            index=models.Index(fields=["user"], name="user_subjec_user_id_a17fdd_idx"),
        ),
        migrations.AddIndex(
            model_name="usersubject",
            index=models.Index(
                fields=["subject"], name="user_subjec_subject_89940d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersubject",
            index=models.Index(fields=["grade"], name="user_subjec_grade_337940_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="usersubject",
            unique_together={("user", "subject")},
        ),
    ]
