# Generated by Django 5.2.1 on 2025-07-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="avatar",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="career_interests",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="county",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="email_notifications",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="marketing_emails",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="preferred_location",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="preferred_study_mode",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="sms_notifications",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="registration_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
