# Generated by Django 5.2.1 on 2025-08-01 22:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "authentication",
            "0004_remove_userprofile_avatar_remove_userprofile_bio_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivity",
            name="request_id",
            field=models.CharField(
                blank=True,
                default=uuid.uuid4,
                help_text="Request ID for tracking",
                max_length=100,
            ),
        ),
    ]
