# Generated by Django 5.2.1 on 2025-08-19 12:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0005_alter_useractivity_request_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
    ]
