# Generated by Django 5.2.1 on 2025-07-21 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "code",
                    models.CharField(
                        help_text="University code (e.g., UON, KU)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("campus", models.CharField(blank=True)),
                ("accreditation", models.CharField(blank=True, max_length=200)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="universities/logos/"
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("public", "Public University"),
                            ("private", "Private University"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "ranking",
                    models.PositiveIntegerField(
                        blank=True, help_text="National ranking", null=True
                    ),
                ),
                (
                    "established_year",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "University",
                "verbose_name_plural": "Universities",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="universitie_name_504812_idx"),
                    models.Index(fields=["code"], name="universitie_code_4bbf30_idx"),
                    models.Index(fields=["city"], name="universitie_city_aff264_idx"),
                    models.Index(
                        fields=["is_active"], name="universitie_is_acti_d3dcd7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faculties",
                        to="universities.university",
                    ),
                ),
            ],
            options={
                "verbose_name": "Faculty",
                "verbose_name_plural": "Faculties",
                "ordering": ["university", "name"],
                "unique_together": {("university", "name")},
            },
        ),
        migrations.CreateModel(
            name="UniversityRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "min_grade",
                    models.CharField(
                        blank=True,
                        help_text="Minimum overall grade required (e.g., B+)",
                        max_length=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="universities.university",
                    ),
                ),
            ],
            options={
                "verbose_name": "University Requirement",
                "verbose_name_plural": "University Requirements",
                "ordering": ["university", "title"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="universities.faculty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "ordering": ["faculty", "name"],
                "unique_together": {("faculty", "name")},
            },
        ),
    ]
