# Generated by Django 5.2.1 on 2026-01-31 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("accreditation", models.CharField(blank=True, max_length=200)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="universities/logos/"
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("public", "Public University"),
                            ("private", "Private University"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("ranking", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "established_year",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Universities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UniversityRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("min_grade", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="general_requirements",
                        to="universities.university",
                    ),
                ),
            ],
            options={
                "ordering": ["university", "title"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255)),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="universities.faculty",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("faculty", "name")},
            },
        ),
    ]
