# Generated by Django 5.2.1 on 2026-03-17 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("city", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "KMTC Campus",
                "verbose_name_plural": "KMTC Campuses",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255)),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="kmtc.faculty",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("faculty", "name")},
            },
        ),
        migrations.CreateModel(
            name="ProgramEntryRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B", "B"),
                            ("B-", "B-"),
                            ("C+", "C+"),
                            ("C", "C"),
                            ("C-", "C-"),
                            ("D+", "D+"),
                            ("D", "D"),
                            ("D-", "D-"),
                            ("E", "E"),
                        ],
                        help_text="Minimum grade for this subject (or alternatives)",
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=True,
                        help_text="This subject (or one of its alternatives) is required",
                    ),
                ),
                (
                    "alternatives",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Subjects that can substitute the primary one",
                        related_name="alternative_for_entry_requirements",
                        to="courses.subject",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_entry_requirements",
                        to="courses.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programme Entry Requirement",
                "verbose_name_plural": "Programme Entry Requirements",
            },
        ),
        migrations.CreateModel(
            name="Programme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("duration", models.CharField(blank=True, max_length=100)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("certificate", "Certificate"),
                            ("diploma", "Diploma"),
                            ("higher_diploma", "Higher Diploma"),
                            ("short_course", "Short Course"),
                        ],
                        default="diploma",
                        max_length=20,
                    ),
                ),
                ("qualification", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "min_mean_grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B", "B"),
                            ("B-", "B-"),
                            ("C+", "C+"),
                            ("C", "C"),
                            ("C-", "C-"),
                            ("D+", "D+"),
                            ("D", "D"),
                            ("D-", "D-"),
                            ("E", "E"),
                        ],
                        help_text="Minimum KCSE mean grade (e.g. 'C', 'C-', 'D+')",
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "is_any_from_group",
                    models.BooleanField(
                        default=False,
                        help_text="User needs ANY of the alternatives (not all)",
                    ),
                ),
                (
                    "required_count_from_group",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=1,
                        help_text="If is_any_from_group=True, how many subjects from alternatives are required (1 or 2)",
                        null=True,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programmes",
                        to="kmtc.department",
                    ),
                ),
                (
                    "required_subjects",
                    models.ManyToManyField(
                        blank=True,
                        related_name="kmtc_programmes",
                        through="kmtc.ProgramEntryRequirement",
                        to="courses.subject",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary required subject (e.g. Biology, English)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="courses.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "KMTC Programme",
                "verbose_name_plural": "KMTC Programmes",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="programentryrequirement",
            name="programme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entry_requirements",
                to="kmtc.programme",
            ),
        ),
        migrations.CreateModel(
            name="OfferedAt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "offered_everywhere",
                    models.BooleanField(
                        default=False,
                        help_text="Check if this programme is offered at ALL KMTC campuses",
                    ),
                ),
                (
                    "campuses",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Leave blank + check 'Offered Everywhere' if available in all campuses",
                        related_name="programmes_offered",
                        to="kmtc.campus",
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offered_at",
                        to="kmtc.programme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programme Offered At",
                "unique_together": {("programme",)},
            },
        ),
    ]
