# Generated by Django 5.2.1 on 2025-08-01 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="campus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "code",
                    models.CharField(
                        help_text="University code (e.g., UON, KU)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "University",
                "verbose_name_plural": "Universities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="campusRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "min_grade",
                    models.CharField(
                        blank=True,
                        help_text="Minimum overall grade required (e.g., B+)",
                        max_length=5,
                    ),
                ),
                (
                    "campo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="kmtc.campus",
                    ),
                ),
            ],
            options={
                "verbose_name": "campus Requirement",
                "verbose_name_plural": "campus Requirements",
                "ordering": ["campo", "title"],
            },
        ),
        migrations.AddField(
            model_name="campus",
            name="campusRequirement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campus",
                to="kmtc.campusrequirement",
            ),
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "campo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faculties",
                        to="kmtc.campus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Faculty",
                "verbose_name_plural": "Faculties",
                "ordering": ["campo", "name"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="kmtc.faculty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "ordering": ["faculty", "name"],
            },
        ),
        migrations.CreateModel(
            name="programmes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        help_text="Duration of the programme (e.g., 4 years)",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programmes",
                        to="kmtc.faculty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programme",
                "verbose_name_plural": "Programmes",
                "ordering": ["faculty", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="campus",
            index=models.Index(fields=["name"], name="kmtc_campus_name_1d241f_idx"),
        ),
        migrations.AddIndex(
            model_name="campus",
            index=models.Index(fields=["code"], name="kmtc_campus_code_01b1fd_idx"),
        ),
        migrations.AddIndex(
            model_name="campus",
            index=models.Index(fields=["city"], name="kmtc_campus_city_fc9c28_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="faculty",
            unique_together={("campo", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("faculty", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="programmes",
            unique_together={("faculty", "name")},
        ),
    ]
