# Generated by Django 5.2.1 on 2026-01-31 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("city", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("requirements", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "KMTC Campus",
                "verbose_name_plural": "KMTC Campuses",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255)),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="kmtc.faculty",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("faculty", "name")},
            },
        ),
        migrations.CreateModel(
            name="Programme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("duration", models.CharField(blank=True, max_length=100)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("certificate", "Certificate"),
                            ("diploma", "Diploma"),
                            ("higher_diploma", "Higher Diploma"),
                            ("short_course", "Short Course"),
                        ],
                        default="diploma",
                        max_length=20,
                    ),
                ),
                ("qualification", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programmes",
                        to="kmtc.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "KMTC Programme",
                "verbose_name_plural": "KMTC Programmes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OfferedAt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "offered_everywhere",
                    models.BooleanField(
                        default=False,
                        help_text="Check if this programme is offered at ALL KMTC campuses",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "campuses",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Leave blank + check 'Offered Everywhere' if available in all campuses",
                        related_name="programmes_offered",
                        to="kmtc.campus",
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offered_at",
                        to="kmtc.programme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programme Offered At",
                "unique_together": {("programme",)},
            },
        ),
    ]
