# Generated by Django 5.2.1 on 2025-08-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kmtc", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campus",
            options={
                "ordering": ["name"],
                "verbose_name": "campus",
                "verbose_name_plural": "campuses",
            },
        ),
        migrations.AlterField(
            model_name="campus",
            name="code",
            field=models.CharField(
                help_text="campus code (e.g., BMT, KAREN)", max_length=20, unique=True
            ),
        ),
    ]
