# Generated by Django 5.2.1 on 2025-08-18 22:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
