# Generated by Django 5.2.1 on 2025-08-23 00:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_alter_subscription_start_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserSubscription",
        ),
    ]
