# Generated by Django 5.2.1 on 2026-01-31 21:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("universities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=300, unique=True)),
                ("details", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("engineering", "Engineering"),
                            ("medicine", "Medicine & Health Sciences"),
                            ("business", "Business & Economics"),
                            ("education", "Education"),
                            ("arts", "Arts & Humanities"),
                            ("sciences", "Pure Sciences"),
                            ("agriculture", "Agriculture"),
                            ("law", "Law"),
                            ("technology", "Information Technology"),
                            ("social_sciences", "Social Sciences"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "typical_duration_years",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("is_core", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Subject",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["is_core"], name="courses_sub_is_core_c20d08_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="courses_sub_is_acti_7c6ad7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProgramSubjectRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "minimum_grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B", "B"),
                            ("B-", "B-"),
                            ("C+", "C+"),
                            ("C", "C"),
                            ("C-", "C-"),
                            ("D+", "D+"),
                            ("D", "D"),
                            ("D-", "D-"),
                            ("E", "E"),
                        ],
                        max_length=2,
                    ),
                ),
                ("is_mandatory", models.BooleanField(default=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_requirements",
                        to="courses.program",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["subject__name"],
                "unique_together": {("program", "subject")},
            },
        ),
        migrations.AddField(
            model_name="program",
            name="required_subjects",
            field=models.ManyToManyField(
                related_name="programs",
                through="courses.ProgramSubjectRequirement",
                to="courses.subject",
            ),
        ),
        migrations.CreateModel(
            name="CourseOffering",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.PositiveIntegerField(unique=True)),
                (
                    "duration_years",
                    models.PositiveIntegerField(
                        help_text="Actual duration at this university (may vary from standard)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "tuition_fee_per_year",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "minimum_grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B", "B"),
                            ("B-", "B-"),
                            ("C+", "C+"),
                            ("C", "C"),
                            ("C-", "C-"),
                            ("D+", "D+"),
                            ("D", "D"),
                            ("D-", "D-"),
                            ("E", "E"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                ("intake_months", models.JSONField(default=list)),
                ("career_prospects", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cluster_requirements",
                    models.TextField(
                        blank=True,
                        help_text="e.g., Cluster 1: Math + Physics + Chemistry",
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offerings",
                        to="universities.university",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offerings",
                        to="courses.program",
                    ),
                ),
            ],
            options={
                "ordering": ["program__name"],
                "indexes": [
                    models.Index(
                        fields=["university"], name="courses_cou_univers_1a0d15_idx"
                    ),
                    models.Index(
                        fields=["tuition_fee_per_year"],
                        name="courses_cou_tuition_e54cd3_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="courses_cou_is_acti_1ed7ce_idx"
                    ),
                ],
                "unique_together": {("program", "university")},
            },
        ),
    ]
